"""empty message

Revision ID: 15d1d01c13ae
Revises: 7853140d86f2
Create Date: 2021-12-19 21:54:16.262349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d1d01c13ae'
down_revision = '7853140d86f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Card', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Card', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
